default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "123456"
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: AWScheduleDB

test:
  <<: *default
  database: AWScheduleDB

production:
  <<: *default
  database: AWScheduleDB
